[target.x86_64-unknown-linux-gnu]
image = "mqrt-build-cross-env:x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "mqrt-build-cross-env:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "mqrt-build-cross-env:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
image = "mqrt-build-cross-env:aarch64-unknown-linux-musl"

[target.armv7-unknown-linux-gnueabihf]
image = "mqrt-build-cross-env:armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-musleabihf]
image = "mqrt-build-cross-env:armv7-unknown-linux-musleabihf"
